version: '3'

services:
  wordpress:
    image: wordpress:latest
    depends_on:
    - db
    volumes:
    - wp_data:/var/www/html
    restart: always
    ports:
    - ":80"
    networks:
    - frontend
    - backend
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    networks:
    - backend
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress 

volumes:
  db_data:
  wp_data:

networks:
  frontend:
  backend:

